### ISSUE TITLE
New placeholders

### ISSUE THREAD

**Issue by wiktor-jozwiak** [GRX005/Velocity-PlayTime#4]
Add new placeholders of type %VPTlink_total% which will return total game time formatted as, for example, 1 year 2 months 3 days 23 hours 34 minutes 13 seconds

**Comment by GRX005** [comment]
You mean like a placeholder that returns the playtime of player "asd123" for ex., all in one?

**Comment by wiktor-jozwiak** [comment]
@GRX005 I mean that this placeholder should returns total formatted playtime

**Comment by GRX005** [comment]
Well I don't get what would be the point of that though, like you can just use the 3 current placeholders to get the total playtime of a player

**Comment by wiktor-jozwiak** [comment]
> Well I don't get what would be the point of that though, like you can just use the 3 current placeholders to get the total playtime of a player

but it is impossible to get days online on the server or months and I have players on the server who have up to 3 months online

**Comment by GRX005** [comment]
Sure, I'll add placeholders for those in the next update.

**Comment by GRX005** [comment]
Added.
