### ISSUE TITLE
Console error message - There's a shaded library that wasn't relocated.

### ISSUE THREAD

**Issue by VoxelDoc** [GRX005/Velocity-PlayTime#5]
Good evening,

I'm building a Velocity proxy, just loaded Liberty Bans, and it gave me this error about Velocity Playtime. I didn't see it mentioned in past messages, so I'd like to let you know about it.

[...] _" Each of the following plugins has shaded a library but did not relocate it. You should report each bug to the plugin author.

Plugin Name | Library Name | Class Detected
----------------------------------------------
Plugin 'velocityplaytime 1.8' | MariaDB-Connector | org.mariadb.jdbc.Driver_"

**Comment by GRX005** [comment]
Should be fixed with the latest update, thanks for reporting.
