### ISSUE TITLE
TopTime Placeholders Bug

### ISSUE THREAD

**Issue by Artugr18** [GRX005/Velocity-PlayTime#8]
%VPTlink_playtime_toptime10_totalhours% and other placeholders that count toptime in minutes and seconds do not work for 10 position
![2024-11-25_16 10 41](https://github.com/user-attachments/assets/3c4b02ae-f39f-4b84-896c-314ed6eaae8c)
![image](https://github.com/user-attachments/assets/373478a6-5fdc-4dd6-9101-27e85aa83ed0)

**Comment by GRX005** [comment]
I see, I'll look into it.

**Comment by GRX005** [comment]
Should be fixed in the latest update.
