### ISSUE TITLE
Add total times to the config

### ISSUE THREAD

**Issue by willywhite0** [GRX005/Velocity-PlayTime#9]
You already added the total times, for example the %VPTlink_playtime_totaldays%, in the PlaytimeLink Plugin.
Is it possible to add like %totaldays% in the config file of the main plugin?

It would be very helpful to have this for the messages of the commands :)

**Comment by GRX005** [comment]
Added just now.

**Comment by willywhite0** [comment]
Oh wow. That was fast, thank you
